version: "3.4"
services:
    database:
        container_name: database
        build:
            context: ./
            dockerfile: ./build/sqlserver.Dockerfile
        ports:
            - "1433:1433"
    elastic-search:
        container_name: elastic-search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    webapi:
        container_name: webapi
        build:
            context: ./WebApi
            dockerfile: Dockerfile
        ports:
            - "5000:80"
            - "5001:443"
        depends_on:
            - database # The web API depends on the database service
    reactapp:
        container_name: reactapp
        build:
            context: ./web-site
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - webapi # The React app depends on the web API service
